version: "3.8"
services:
  db:
    image: mysql
    container_name: mysql-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: auto102030
      MYSQL_DATABASE: autokb
    ports:
      - "3306:3306"
    networks:
      - autokb-net
    volumes:
      - ../db:/var/lib/mysql
  backend:
    container_name: backend
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: kb-auto/backend:latest
    env_file:
      - ./.env
    restart: unless-stopped
    links:
      - db
    depends_on:
      - db
    ports:
      - "3333:3333"
    networks:
      - autokb-net

networks:
  autokb-net:
    driver: bridge
